apiVersion: v1
kind: Pod
metadata:
  annotations: {{}}
spec:
  containers:
    - name: runtime
      image: "{EXEC_RUNTIME}"
      securityContext:
        privileged: true
      env:
        - name: DOCKER_HOST
          value: tcp://127.0.0.1:2375
      imagePullPolicy: "{IMAGE_PULL_POLICY}"
      volumeMounts:
        - mountPath: /var/lib/docker
          name: docker-storage
      startupProbe:
        httpGet:
          port: 2375
          path: _ping
        periodSeconds: 1
      livenessProbe:
        httpGet:
          port: 2375
          path: _ping
    - name: engine
      image: "{EXEC_ENGINE}"
      ports:
        - containerPort: 8888
      env:
        - name: DOCKER_HOST
          value: 127.0.0.1
        - name: DOCKER_PORT
          value: "2375"
      imagePullPolicy: "{IMAGE_PULL_POLICY}"
      volumeMounts:
        - mountPath: /var/lib/docker
          name: docker-storage
        - mountPath: /etc/podinfo
          name: podinfo
      startupProbe:
        httpGet:
          port: 8888
        periodSeconds: 1
      livenessProbe:
        httpGet:
          port: 8888
    - name: interface
      image: "{EXEC_INTERFACE}"
      ports:
        - containerPort: 2222
      env:
        - name: USER_NAME
          value: rsync
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
      imagePullPolicy: "{IMAGE_PULL_POLICY}"
      volumeMounts:
        - mountPath: /var/lib/docker
          name: docker-storage
      startupProbe:
        tcpSocket:
          port: 2222
        periodSeconds: 1
      livenessProbe:
        tcpSocket:
          port: 2222
  volumes:
    - name: docker-storage
      emptyDir:
        medium: Memory
    - name: podinfo
      downwardAPI:
        items:
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
