apiVersion: v1
kind: Pod
metadata:
  annotations: {{}}
spec:
  containers:
    - name: interface
      image: "{EXEC_INTERFACE}"
      ports:
        - containerPort: 2222
      env:
        - name: USER_NAME
          value: rsync
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
      imagePullPolicy: "{IMAGE_PULL_POLICY}"
      startupProbe:
        tcpSocket:
          port: 2222
        periodSeconds: 1
      livenessProbe:
        tcpSocket:
          port: 2222
  volumes:
    - name: image-storage
      emptyDir:
        medium: Memory
